name = "dkuzeit"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-02-06"
compatibility_flags = ["nodejs_compat"]
routes = [{ pattern = "dkuzeit.net", custom_domain = true }]

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[version_metadata]
binding = "CF_VERSION_METADATA"

[dev]
port = 8787

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"